name: Deploy Develop

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    name: Build and test
  
  deploy:
    name: Deploy Docker image
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@v1
        continue-on-error: true
        with:
          url: 'https://testbot.api.macro-deck.app/webhook/deploy'
          method: 'POST'
          bearerToken: ${{ secrets.TESTBOT_WEBHOOK_DEPLOY_KEY }}
          customHeaders: '{"Content-Type": "application/json" }'
          data: '{"toEveryone":false,"embed":{"color":{"r":0,"g":1,"b":0},"description":"MacroBot updating to ${{ github.sha }}.","fields":[{"name":"Branch","value":"Develop","inline":false},{"name":"SHA","value":"${{ github.sha }}","inline":false}]}}'

      - name: Updating the image on the server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.GITHUBWORKFLOWS_USER }}
          password: ${{ secrets.GITHUBWORKFLOWS_USER_PASSWORD }}
          port: ${{ secrets.DOCKER_HOST_PORT }}
          script: |
            cd "scripts/macro-bot/"
            ./update_develop.sh ${{ github.sha }}