name: Deploy Production

on:
  release:
    types: [published]
      
jobs:
  tests:
    uses: ./.github/workflows/build.yml
    name: Build and test
  deploy:
    name: Build and deploy Docker image
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: MacroBotApp/MacroBotApp.csproj
    - name: Build the Docker image
      run: docker build . --file MacroBotApp/Dockerfile --tag suchbyte/macro-bot:${{steps.get-version.outputs.version}}
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@219c305e1ce92a755f3aa4ba17387c95df31e987
      with:
        registry: docker.io
        username: suchbyte
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: docker push suchbyte/macro-bot:${{steps.get-version.outputs.version}}
    - name: Updating the image on the server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DOCKER_HOST }}
        username: ${{ secrets.GITHUBWORKFLOWS_USER }}
        password: ${{ secrets.GITHUBWORKFLOWS_USER_PASSWORD }}
        port: ${{ secrets.DOCKER_HOST_PORT }}
        script: |
          cd "scripts/Macro Bot/"
          ./update_production.sh ${{steps.get-version.outputs.version}}
