name: Deploy Develop

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
      
jobs:
  tests:
    uses: ./.github/workflows/build.yml
    name: Build and test
  deploy:
    name: Build and deploy Docker image
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://testbot.api.macro-deck.app/webhook/deploy'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.TESTBOT_WEBHOOK_DEPLOY_KEY}}" }'
        data: '{"title":"Deployment started","toEveryone":true,"embed":{"color":{"r":0,"g":1,"b":1},"description":"Deployment of the current develop branch started","fields":[{"name":"SHA","value":"${{ github.sha }}","inline":false}]}}'
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file MacroBotApp/Dockerfile --tag suchbyte/macro-bot:dev_${{ github.sha }}
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: docker.io
        username: suchbyte
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: docker push suchbyte/macro-bot:dev_${{ github.sha }}
    - name: Updating the image on the server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DOCKER_HOST }}
        username: ${{ secrets.GITHUBWORKFLOWS_USER }}
        password: ${{ secrets.GITHUBWORKFLOWS_USER_PASSWORD }}
        port: ${{ secrets.DOCKER_HOST_PORT }}
        script: |
          cd "scripts/Macro Bot/"
          ./update_develop.sh dev_${{ github.sha }}
