name: Deploy Develop

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
      
jobs:
  tests:
    uses: ./.github/workflows/build.yml
    name: Build and test
  deploy:
    name: Build and deploy Docker image
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://testbot.api.macro-deck.app/webhook/deploy'
        method: 'POST'
        bearerToken:  ${{ secrets.TESTBOT_WEBHOOK_DEPLOY_KEY }}
        customHeaders: '{"Content-Type": "application/json" }'
        data: '{"toEveryone":false,"embed":{"color":{"r":0,"g":1,"b":1},"description":"Deployment started, building and pushing the image...","fields":[{"name":"SHA","value":"${{ github.sha }}","inline":false}]}}'
    - name: Build the Docker image
      run: docker build . --file MacroBotApp/Dockerfile --tag suchbyte/macro-bot:dev_${{ github.sha }}
    - name: Log into registry
      uses: docker/login-action@219c305e1ce92a755f3aa4ba17387c95df31e987
      with:
        registry: docker.io
        username: suchbyte
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: docker push suchbyte/macro-bot:dev_${{ github.sha }}
    - uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://testbot.api.macro-deck.app/webhook/deploy'
        method: 'POST'
        bearerToken:  ${{ secrets.TESTBOT_WEBHOOK_DEPLOY_KEY }}
        customHeaders: '{"Content-Type": "application/json" }'
        data: '{"toEveryone":false,"embed":{"color":{"r":0,"g":1,"b":0},"description":"Push successful, updating the container now...","fields":[{"name":"SHA","value":"${{ github.sha }}","inline":false}]}}'
    - name: Updating the image on the server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DOCKER_HOST }}
        username: ${{ secrets.GITHUBWORKFLOWS_USER }}
        password: ${{ secrets.GITHUBWORKFLOWS_USER_PASSWORD }}
        port: ${{ secrets.DOCKER_HOST_PORT }}
        script: |
          cd "scripts/Macro Bot/"
          ./update_develop.sh dev_${{ github.sha }}
