name: Integration Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: macrobotmaster
          POSTGRES_PASSWORD: test
          POSTGRES_DB: macrobotintegrationtest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Pull the base image
      #  run: docker pull ghcr.io/macro-deck-app/macro-bot-base:${{ github.sha }}

      #- name: Run Tests inside Docker container
      #  run: >
      #    docker run --rm --network="host" --env ASPNETCORE_ENVIRONMENT=GitHubIntegrationTest
      #    ghcr.io/macro-deck-app/macro-bot-base:${{ github.sha }}
      #    dotnet test "tests/MacroBot.Tests.IntegrationTests/MacroBot.Tests.IntegrationTests.csproj"