name: Deploy Develop

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
      
jobs:
  deploy:
    name: Build and deploy Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Webhook
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://testbot.api.macro-deck.app/webhook/deploy'
        method: 'POST'
        bearerToken:  ${{ secrets.TESTBOT_WEBHOOK_DEPLOY_KEY }}
        customHeaders: '{"Content-Type": "application/json" }'
        data: '{"toEveryone":false,"embed":{"color":{"r":0,"g":1,"b":1},"description":"Deployment successful, updating the container now...","fields":[{"name":"SHA","value":"${{ github.sha }}","inline":false}]}}'
